apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  #replica set labels
  labels:
    purpose: deployment-demo
    project: roboshop
    app: nginx
spec:
  replicas: 2 #we can give number here as many as we want
  # These are the labels replicaset uses to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      purpose: deployment-demo
      project: roboshop
      app: nginx
    # this is pod defination
  template:
    metadata:
      labels:
        purpose: deployment-demo
        project: roboshop
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable-per1